becowo_core_homepage:
    path:     /
    defaults: { _controller: BecowoCoreBundle:Home:home }
    methods: GET

# becowo_core_list_workspaces:
#     path:     /list
#     defaults: { _controller: BecowoCoreBundle:Home:paginationList }
#     methods: GET
#     options:
#         expose: true

becowo_core_workspace:
    path:     /espace-de-coworking/{region}/{ville}/{name}
    defaults: { _controller: BecowoCoreBundle:Workspace:view }
    methods: GET|POST
    options:
        expose: true

becowo_core_workspace_contact:
    path:     /contact/{name}
    defaults: { _controller: BecowoCoreBundle:Workspace:contact }
    methods: GET|POST
    options:
        expose: true

becowo_core_workspace_edit_create:
    path:     /espace-de-coworking/{id}
    defaults: { _controller: BecowoCoreBundle:Workspace:editCreateWsFull }
    methods: GET|POST

becowo_core_workspace_upload_pictures:
    path:     /espace-de-coworking/upload/{wsId}
    defaults: { _controller: BecowoCoreBundle:Workspace:uploadPictureDropzone }
    methods: GET|POST

becowo_core_workspace_delete_picture_uploaded:
    path:     /espace-de-coworking/upload/delete/{wsId}/{pictureName}
    defaults: { _controller: BecowoCoreBundle:Workspace:deletePictureUploaded }
    methods: GET|POST
    options:
        expose: true

becowo_core_community:
    path:     /communaute/coworkers
    defaults: { _controller: BecowoCoreBundle:Community:community }
    methods: GET

becowo_member_community_coworker:
    path:     /communaute/coworkers/{city}-{job}-{id}
    defaults: { _controller: BecowoMemberBundle:Member:viewPublicProfile }
    methods: GET|POST

becowo_core_community_events:
    path:     /communaute/events
    defaults: { _controller: BecowoCoreBundle:Community:events }
    methods: GET

becowo_core_booking_myreservations:
    path: /booking
    defaults: { _controller: BecowoCoreBundle:Booking:myReservations }
    methods: GET

becowo_core_offers:
    path:     /offres
    defaults: { _controller: BecowoCoreBundle:Offer:view }
    methods: GET|POST

# becowo_core_offers_contact:
#     path:     /offres/{name}
#     defaults: { _controller: BecowoCoreBundle:Offer:contact }
#     methods: GET

becowo_core_comment_ca_marche_coworkers:
    path:     /comment-ca-marche-coworker
    defaults: { _controller: BecowoCoreBundle:Footer:commentCaMarcheCoworkers }
    methods: GET

becowo_core_comment_ca_marche_espaces:
    path:     /comment-ca-marche-espaces
    defaults: { _controller: BecowoCoreBundle:Footer:commentCaMarcheEspaces }
    methods: GET

becowo_core_vote_zen:
    path:     /voteZen/{id}
    defaults: { _controller: BecowoCoreBundle:Vote:voteWSdevenirZen }
    methods: GET|POST
    options:
        expose: true

becowo_core_contact:
    path:     /contact
    defaults: { _controller: BecowoCoreBundle:Footer:contact }
    methods: GET|POST

becowo_core_quisommesnous:
    path:     /qui-sommes-nous
    defaults: { _controller: BecowoCoreBundle:Footer:quiSommesNous }
    methods: GET

becowo_core_faq:
    path:     /faq
    defaults: { _controller: BecowoCoreBundle:Footer:faq }
    methods: GET

becowo_core_cgu:
    path:     /cgu
    defaults: { _controller: BecowoCoreBundle:Footer:cgu }
    methods: GET

becowo_core_mentions:
    path:     /mentions-legales
    defaults: { _controller: BecowoCoreBundle:Footer:mentions }
    methods: GET

becowo_core_cookies:
    path:     /cookies
    defaults: { _controller: BecowoCoreBundle:Footer:cookies }
    methods: GET

becowo_core_paiement:
    path:     /paiement-en-ligne
    defaults: { _controller: BecowoCoreBundle:Footer:paiement }
    methods: GET

becowo_core_booking_list:
    path:     /booking-list/{name}
    defaults: { _controller: BecowoCoreBundle:Booking:bookingList }
    methods: GET

becowo_core_booking:
    path:     /booking/{id}
    defaults: { _controller: BecowoCoreBundle:Booking:book }
    methods: GET|POST

becowo_core_booking_validated:
    path:     /book/validated/{bookRef}
    defaults: { _controller: BecowoCoreBundle:Booking:validate }
    methods: GET|POST

becowo_core_booking_refused:
    path:     /book/refused/{bookRef}
    defaults: { _controller: BecowoCoreBundle:Booking:refuse }
    methods: GET|POST

becowo_core_paiement_call_bank:
    path:     /bank
    defaults: { _controller: BecowoCoreBundle:Paiement:callBank }
    methods: GET|POST
    options:
        expose: true

becowo_core_paiement_effectue:
    path:     /paiement/effectue
    defaults: { _controller: BecowoCoreBundle:Paiement:effectue }
    methods: GET

becowo_core_paiement_annule:
    path:     /paiement/annule
    defaults: { _controller: BecowoCoreBundle:Paiement:annule }
    methods: GET

becowo_core_paiement_refuse:
    path:     /paiement/refuse
    defaults: { _controller: BecowoCoreBundle:Paiement:refuse }
    methods: GET

becowo_core_paiement_ipn:
    path:     /paiement/ipn
    defaults: { _controller: BecowoCoreBundle:Paiement:ipn }
    methods: GET

becowo_core_visit_360:
    path:     /{name}/visit-360
    defaults: { _controller: BecowoCoreBundle:Workspace:visit }

becowo_core_blog_last_article:
    path:     /blog/{nbArticles}
    defaults: { _controller: BecowoCoreBundle:Blog:viewLastArticle }

# becowo_core_ambassadeur:
#     path:     /devenir-ambassadeur
#     defaults: { _controller: BecowoCoreBundle:Footer:ambassadeur }
#     methods: GET

# becowo_core_declare_ws:
#     path:     /declarer-un-espace
#     defaults: { _controller: BecowoCoreBundle:Header:declarerEspace }
#     methods: GET

becowo_core_extract:
    path:     /extract
    defaults: { _controller: BecowoCoreBundle:Extract:extract }
    methods: GET

becowo_comment:
    path:    /comment/{id}
    defaults: { _controller: BecowoCoreBundle:Workspace:voteAndComment }
    methods: GET|POST
    options:
        expose: true

becowo_core_debug:
    path:     /debug
    defaults: { _controller: BecowoCoreBundle:Debug:view }
    methods: GET

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
