becowo_core_homepage:
    path:     /
    defaults: { _controller: BecowoCoreBundle:Home:home }
    methods: GET

becowo_core_workspace:
    path:     /ws/{name}
    defaults: { _controller: BecowoCoreBundle:Workspace:view }
    methods: GET|POST
    options:
        expose: true

becowo_core_booking_myreservations:
    path: /booking
    defaults: { _controller: BecowoCoreBundle:Booking:myReservations }

becowo_core_offers:
    path:     /offres
    defaults: { _controller: BecowoCoreBundle:Offer:view }

becowo_core_offers_contact:
    path:     /offres/{name}
    defaults: { _controller: BecowoCoreBundle:Offer:contact }

becowo_core_vote:
    path:     /vote/{name}
    defaults: { _controller: BecowoCoreBundle:Vote:vote }
    methods: GET|POST
    options:
        expose: true

becowo_core_contact:
    path:     /contact
    defaults: { _controller: BecowoCoreBundle:Footer:Contact }

becowo_core_apropos:
    path:     /apropos
    defaults: { _controller: BecowoCoreBundle:Footer:Apropos }

becowo_core_faq:
    path:     /faq
    defaults: { _controller: BecowoCoreBundle:Footer:Faq }

becowo_core_cgv:
    path:     /cgv
    defaults: { _controller: BecowoCoreBundle:Footer:Cgv }

becowo_core_mentions:
    path:     /mentions-legales
    defaults: { _controller: BecowoCoreBundle:Footer:Mentions }

becowo_core_paiement:
    path:     /paiement-en-ligne
    defaults: { _controller: BecowoCoreBundle:Footer:Paiement }

becowo_core_ambassadeur:
    path:     /devenir-ambassadeur
    defaults: { _controller: BecowoCoreBundle:Footer:Ambassadeur }

becowo_core_declare_ws:
    path:     /declarer-un-espace
    defaults: { _controller: BecowoCoreBundle:Header:DeclarerEspace }

becowo_member_public_profile:
    path:     /profile/public/{username}
    defaults: { _controller: BecowoMemberBundle:Member:viewPublicProfile }

becowo_search:
    path:    /search
    defaults: { _controller: BecowoCoreBundle:Search:search }
    methods: GET|POST
    options:
        expose: true

becowo_comment:
    path:    /comment
    defaults: { _controller: BecowoCoreBundle:Comment:view }
    methods: GET|POST
    options:
        expose: true

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
