becowo_core_homepage:
    path:     /
    defaults: { _controller: BecowoCoreBundle:Home:home }
    methods: GET

becowo_core_workspace:
    path:     /ws/{name}
    defaults: { _controller: BecowoCoreBundle:Workspace:view }
    methods: GET|POST
    options:
        expose: true

becowo_core_booking_myreservations:
    path: /booking
    defaults: { _controller: BecowoCoreBundle:Booking:myReservations }
    methods: GET

becowo_core_offers:
    path:     /offres
    defaults: { _controller: BecowoCoreBundle:Offer:view }
    methods: GET

becowo_core_offers_contact:
    path:     /offres/{name}
    defaults: { _controller: BecowoCoreBundle:Offer:contact }
    methods: GET

becowo_core_vote:
    path:     /vote/{name}
    defaults: { _controller: BecowoCoreBundle:Vote:vote }
    methods: GET|POST
    options:
        expose: true

becowo_core_contact:
    path:     /contact
    defaults: { _controller: BecowoCoreBundle:Footer:contact }
    methods: GET

becowo_core_apropos:
    path:     /apropos
    defaults: { _controller: BecowoCoreBundle:Footer:aPropos }
    methods: GET

becowo_core_faq:
    path:     /faq
    defaults: { _controller: BecowoCoreBundle:Footer:faq }
    methods: GET

becowo_core_cgu:
    path:     /cgu
    defaults: { _controller: BecowoCoreBundle:Footer:cgu }
    methods: GET

becowo_core_cookies:
    path:     /cookies
    defaults: { _controller: BecowoCoreBundle:Footer:cookies }
    methods: GET

becowo_core_paiement:
    path:     /paiement-en-ligne
    defaults: { _controller: BecowoCoreBundle:Footer:paiement }
    methods: GET

becowo_core_booking_form:
    path:     /ws/{name}
    defaults: { _controller: BecowoCoreBundle:Booking:bookForm }
    methods: GET|POST
    options:
        expose: true

becowo_core_booking:
    path:     /ws/{name}/book
    defaults: { _controller: BecowoCoreBundle:Booking:book }
    methods: GET|POST
    options:
        expose: true

becowo_core_booking_validated:
    path:     /book/validated/{bookRef}
    defaults: { _controller: BecowoCoreBundle:Booking:validate }
    methods: GET|POST

becowo_core_booking_refused:
    path:     /book/refused/{bookRef}
    defaults: { _controller: BecowoCoreBundle:Booking:refuse }
    methods: GET|POST

becowo_core_paiement_effectue:
    path:     /ws/paiement/effectue
    defaults: { _controller: BecowoCoreBundle:Paiement:effectue }
    methods: GET|POST

becowo_core_paiement_annule:
    path:     /ws/paiement/annule
    defaults: { _controller: BecowoCoreBundle:Paiement:annule }
    methods: GET|POST

becowo_core_paiement_refuse:
    path:     /ws/paiement/refuse
    defaults: { _controller: BecowoCoreBundle:Paiement:refuse }
    methods: GET|POST

becowo_core_paiement_ipn:
    path:     /ws/paiement/ipn
    defaults: { _controller: BecowoCoreBundle:Paiement:ipn }
    methods: GET|POST

becowo_core_visit_360:
    path:     /ws/{name}/visit-360
    defaults: { _controller: BecowoCoreBundle:Workspace:visit }

# becowo_core_ambassadeur:
#     path:     /devenir-ambassadeur
#     defaults: { _controller: BecowoCoreBundle:Footer:ambassadeur }
#     methods: GET

becowo_core_declare_ws:
    path:     /declarer-un-espace
    defaults: { _controller: BecowoCoreBundle:Header:declarerEspace }
    methods: GET

becowo_core_map:
    path:     /map
    defaults: { _controller: BecowoCoreBundle:Map:view }
    methods: GET|POST

becowo_core_extract:
    path:     /extract
    defaults: { _controller: BecowoCoreBundle:Extract:extract }
    methods: GET

becowo_member_public_profile:
    path:     /profile/public/{username}
    defaults: { _controller: BecowoMemberBundle:Member:viewPublicProfile }
    methods: GET

becowo_search:
    path:    /search
    defaults: { _controller: BecowoCoreBundle:Search:search }
    methods: GET
    options:
        expose: true

becowo_comment:
    path:    /comment/{name}
    defaults: { _controller: BecowoCoreBundle:Comment:view }
    methods: GET|POST
    options:
        expose: true

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
