becowo_core_homepage:
    path:     /
    defaults: { _controller: BecowoCoreBundle:Home:home }

becowo_core_contact:
    path:     /contact
    defaults: { _controller: BecowoCoreBundle:Contact:Contact }
