becowo_core_homepage:
    path:     /
    defaults: { _controller: BecowoCoreBundle:Home:home }
    methods: GET

becowo_core_workspace:
    path:     /ws/{name}
    defaults: { _controller: BecowoCoreBundle:Workspace:view }
    methods: GET|POST
    options:
        expose: true

becowo_core_workspace_vote:
    path:     /vote/{vote}{name}{member}
    defaults: { _controller: BecowoCoreBundle:Workspace:vote }
    requirements:
        vote: \d+
    options:
        expose: true

becowo_core_booking_myreservations:
    path: /booking
    defaults: { _controller: BecowoCoreBundle:Booking:myReservations }

becowo_core_offers:
    path:     /offres
    defaults: { _controller: BecowoCoreBundle:Offer:view }

becowo_core_offers_contact:
    path:     /offres/{name}
    defaults: { _controller: BecowoCoreBundle:Offer:contact }

becowo_core_contact:
    path:     /contact
    defaults: { _controller: BecowoCoreBundle:Footer:Contact }

becowo_core_apropos:
    path:     /apropos
    defaults: { _controller: BecowoCoreBundle:Footer:Apropos }

becowo_core_faq:
    path:     /faq
    defaults: { _controller: BecowoCoreBundle:Footer:Faq }

becowo_member_public_profile:
    path:     /profile/public/{username}
    defaults: { _controller: BecowoMemberBundle:Member:viewPublicProfile }

becowo_search:
    path:    /search
    defaults: { _controller: BecowoCoreBundle:Search:search }
    methods: GET|POST

# recherche:
#     path:   /search
#     defaults: { _controller: BecowoCoreBundle:Search:search }
#     methods: GET

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
