becowo_manager:
    resource: "@BecowoManagerBundle/Resources/config/routing.yml"
    prefix:   /manager/

becowo_core:
    resource: "@BecowoCoreBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# -> from @FOSUserBundle/Resources/routing/profile.xml
# je surcharge pour ne pas utiliser la view show, mais uniquement edit

fos_user_profile_show:
    path: /profile/show
    defaults: { _controller: FOSUserBundle:Profile:edit }
    requirements:
        _method: GET|POST

fos_user_profile_edit:
    path: /profile/edit
    defaults: { _controller: FOSUserBundle:Profile:edit }
    requirements:
        _method: GET|POST

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

# HWIOAuthBundle : connexion via FB...
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /connect
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
 
# We override this part of the routing
hwi_oauth_connect:
    resource: "@BecowoMemberBundle/Resources/config/connect.xml"
    prefix: /connect
    
facebook_login:
    path: /connect/check-facebook
