security:
  encoders:
    Becowo\MemberBundle\Entity\Member: plaintext

  role_hierarchy:
    ROLE_MANAGER:     ROLE_USER
    ROLE_ADMIN:       [ROLE_USER, ROLE_MANAGER]
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:
        entity:
            class:  Becowo\MemberBundle\Entity\Member
            property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern:   ^/
      anonymous: true
      provider:     main
      form_login:
        login_path: becowo_member_login
        check_path: becowo_member_login_check
      logout:
        path:       becowo_member_logout
        target:     /

  access_control:
    - { path: ^/manager, roles: ROLE_MANAGER }
    - { path: ^/admin, roles: ROLE_ADMIN }
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
