security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext

  role_hierarchy:
    ROLE_MANAGER:     ROLE_USER
    ROLE_ADMIN:       [ROLE_USER, ROLE_MANAGER]
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    in_memory:
      memory:
        users:
          user:  { password: userpass, roles: [ 'ROLE_USER' ] }
          admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
          manager: { password: managerpass, roles: [ 'ROLE_MANAGER' ] }

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern:   ^/
      anonymous: true
      provider:     in_memory
      form_login:
        login_path: becowo_member_login
        check_path: becowo_member_login_check
      logout:
        path:       becowo_member_logout
        target:     /

  access_control:
    - { path: ^/manager, roles: ROLE_MANAGER }
    - { path: ^/admin, roles: ROLE_ADMIN }
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
