security:
  encoders:
    Becowo\MemberBundle\Entity\Member: sha512

  role_hierarchy:
    ROLE_MANAGER:     ROLE_USER
    ROLE_ADMIN:       [ROLE_USER, ROLE_MANAGER]
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:
        id: fos_user.user_provider.username_email

  firewalls:
    secured_area:
            anonymous: ~
            logout: true
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    linkedin:           "/login/check-linkedin"
                    twitter:           "/login/check-twitter"
                login_path:        /login
                use_forward:       false
                failure_path:      /login
                oauth_user_provider:
                  service: app.HWIOAuth.user_provider
            form_login:
              login_path: fos_user_security_login
              check_path: fos_user_security_check
              always_use_default_target_path : false
              default_target_path : /
              target_path_parameter : _target_path
              use_referer : true
              success_handler: authentication_handler 
            remember_me:
              secret:     '%secret%' # %secret% est un paramètre de parameter
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main: # non utilisé ? (form_login remis dans secured_area pour combiner FOS et HWI)
      pattern:   ^/
      anonymous: true
      provider:     main
      # form_login:
      #   login_path: fos_user_security_login
      #   check_path: fos_user_security_check
      logout:
        path:       fos_user_security_logout
        target:     /
      # remember_me:
      #   secret:     %secret% # %secret% est un paramètre de parameter


  access_control:
    - { path: ^/manager, roles: ROLE_MANAGER }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/booking, roles: ROLE_USER }
    - { path: ^/bank, roles: ROLE_USER }
    - { path: ^/debug, roles: ROLE_ADMIN }
    # - { path: ^/login, roles: ROLE_ADMIN }
    # - { path: ^/register, roles: ROLE_ADMIN}
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
