# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.registration:
        class: Becowo\MemberBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: app_user_profile }

    app.search:
        class: Becowo\CoreBundle\Services\SearchEngine
        arguments:    ['@fos_elastica.finder.becowo.workspace']

