# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.registration:
        class: Becowo\MemberBundle\Form\Type\ProfileType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: app_user_profile }

    # app.search:
    #     class: Becowo\CoreBundle\Services\SearchEngine
    #     arguments:    ['@fos_elastica.finder.becowo.workspace']

    app.workspace:
        class: Becowo\CoreBundle\Services\WorkspaceService
        arguments: ['@doctrine.orm.entity_manager']

    app.comment:
        class: Becowo\CoreBundle\Services\CommentService
        arguments: ['@doctrine.orm.entity_manager']

    app.error:
        class: Becowo\CoreBundle\Services\ErrorService
        arguments: ['@doctrine.orm.entity_manager']

    # app.paiement:
    #     class: Becowo\CoreBundle\Services\PaiementService
    #     arguments: ['@doctrine.orm.entity_manager']

    app.member:
        class: Becowo\MemberBundle\Services\Member
        arguments: ['@doctrine.orm.entity_manager']      

    app.map:
        class: Becowo\CoreBundle\Services\Map
        arguments: ['@doctrine.orm.entity_manager'] 

    app.manager.dashboard:
        class: Becowo\ManagerBundle\Services\Dashboard
        arguments: ['@doctrine.orm.entity_manager'] 

    app.HWIOAuth.user_provider:
        class:        Becowo\MemberBundle\Services\MyFOSUBUserProvider
        arguments: ['@fos_user.user_manager', { facebook: facebook_id }]

    price.lowestPrice :
        class:  Becowo\CoreBundle\EventListener\PriceListener
        arguments: ['@service_container']
        tags: 
            - { name: doctrine.orm.entity_listener }
    
    comment.voteAverage :
        class:  Becowo\CoreBundle\EventListener\CommentListener
        arguments: ['@service_container']
        tags: 
            - { name: doctrine.orm.entity_listener }

    picture.favorite :
        class:  Becowo\CoreBundle\EventListener\PictureListener
        arguments: ['@service_container']
        tags: 
            - { name: doctrine.orm.entity_listener }    

    app.api :
        class: Becowo\ApiBundle\Services\ApiService
        arguments: ['@doctrine.orm.entity_manager', %facebook_client_id%, %facebook_client_secret%, '@app.workspace', '@logger'] 

    app.member.sendEmailNewUsers :
        class: Becowo\MemberBundle\Controller\MemberController
        arguments: ['@doctrine.orm.entity_manager'] 
