becowo_manager_profile:
    path:     /profile
    defaults: { _controller: BecowoManagerBundle:Profile:view }
    methods: GET|POST

becowo_manager_profile_desc:
    path:     /profile/desc
    defaults: { _controller: BecowoManagerBundle:Profile:desc }
    methods: GET|POST

becowo_manager_profile_pictures:
    path:     /profile/pictures
    defaults: { _controller: BecowoManagerBundle:Profile:pictures }
    methods: GET|POST

becowo_manager_profile_amenities:
    path:     /profile/equipements
    defaults: { _controller: BecowoManagerBundle:Profile:amenities }
    methods: GET|POST

becowo_manager_profile_offices:
    path:     /profile/bureaux
    defaults: { _controller: BecowoManagerBundle:Profile:offices }
    methods: GET|POST

becowo_manager_dashboard:
    path:     /dashboard
    defaults: { _controller: BecowoManagerBundle:Dashboard:view }

becowo_manager_booking:
    path:     /booking
    defaults: { _controller: BecowoManagerBundle:Booking:view }

becowo_manager_contracts:
    path:     /contracts
    defaults: { _controller: BecowoManagerBundle:Contracts:view }

becowo_manager_bills:
    path:     /bills
    defaults: { _controller: BecowoManagerBundle:Bills:view }
